// Collection of motivational quotes for the Boss Face
// These rotate randomly on each page load
// Quotes are kept concise to fit in the speech bubble

export const bossQuotes = [
    // Steve Jobs
    { quote: "Focus is about saying no.", author: "Steve Jobs" },
    { quote: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
    { quote: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs" },
    { quote: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
    { quote: "Your time is limited. Don't waste it living someone else's life.", author: "Steve Jobs" },

    // Marcus Aurelius (Stoic)
    { quote: "The obstacle is the way.", author: "Marcus Aurelius" },
    { quote: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
    { quote: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius" },
    { quote: "Very little is needed to make a happy life.", author: "Marcus Aurelius" },
    { quote: "Accept the things to which fate binds you.", author: "Marcus Aurelius" },
    { quote: "Begin each day telling yourself: Today I shall meet interference, ingratitude, and disloyalty.", author: "Marcus Aurelius" },
    { quote: "How much time he gains who does not look to see what his neighbor says or does.", author: "Marcus Aurelius" },
    { quote: "Confine yourself to the present.", author: "Marcus Aurelius" },
    { quote: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
    { quote: "You have power over your mind—not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },

    // Seneca (Stoic)
    { quote: "We suffer more often in imagination than in reality.", author: "Seneca" },
    { quote: "Begin at once to live.", author: "Seneca" },
    { quote: "It is not that we have a short time to live, but that we waste much of it.", author: "Seneca" },
    { quote: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
    { quote: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
    { quote: "He who is brave is free.", author: "Seneca" },
    { quote: "While we wait for life, life passes.", author: "Seneca" },
    { quote: "The greatest obstacle to living is expectancy.", author: "Seneca" },
    { quote: "True happiness is to enjoy the present.", author: "Seneca" },
    { quote: "It is not the man who has too little that is poor, but the one who craves more.", author: "Seneca" },

    // Epictetus (Stoic)
    { quote: "First say to yourself what you would be; then do what you have to do.", author: "Epictetus" },
    { quote: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
    { quote: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
    { quote: "No man is free who is not master of himself.", author: "Epictetus" },
    { quote: "Make the best use of what is in your power.", author: "Epictetus" },
    { quote: "Only the educated are free.", author: "Epictetus" },
    { quote: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
    { quote: "Circumstances don't make the man, they only reveal him to himself.", author: "Epictetus" },
    { quote: "If you want to improve, be content to be thought foolish.", author: "Epictetus" },
    { quote: "Know first who you are and then adorn yourself accordingly.", author: "Epictetus" },

    // Buddha & Buddhist Wisdom
    { quote: "The mind is everything. What you think you become.", author: "Buddha" },
    { quote: "There is no path to happiness: happiness is the path.", author: "Buddha" },
    { quote: "Every morning we are born again. What we do today is what matters most.", author: "Buddha" },
    { quote: "Peace comes from within. Do not seek it without.", author: "Buddha" },
    { quote: "The root of suffering is attachment.", author: "Buddha" },
    { quote: "Holding on to anger is like drinking poison.", author: "Buddha" },
    { quote: "An idea that is developed and put into action is more important than one that exists only as an idea.", author: "Buddha" },
    { quote: "You yourself must strive. The Buddhas only point the way.", author: "Buddha" },
    { quote: "To keep the body in good health is a duty.", author: "Buddha" },
    { quote: "The trouble is, you think you have time.", author: "Buddha" },

    // Zen & Eastern Proverbs
    { quote: "Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.", author: "Zen Proverb" },
    { quote: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { quote: "When the student is ready, the teacher will appear.", author: "Zen Proverb" },
    { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { quote: "A gem cannot be polished without friction.", author: "Chinese Proverb" },
    { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { quote: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Japanese Proverb" },
    { quote: "Be not afraid of going slowly, be afraid only of standing still.", author: "Chinese Proverb" },
    { quote: "When there is no enemy within, the enemies outside cannot hurt you.", author: "African Proverb" },
    { quote: "The quieter you become, the more you can hear.", author: "Ram Dass" },

    // Writers - Hemingway
    { quote: "There is nothing to writing. All you do is sit down and bleed.", author: "Ernest Hemingway" },
    { quote: "Courage is grace under pressure.", author: "Ernest Hemingway" },
    { quote: "The world breaks everyone, and afterward, some are strong at the broken places.", author: "Ernest Hemingway" },
    { quote: "Never confuse movement with action.", author: "Ernest Hemingway" },
    { quote: "The best way to find out if you can trust somebody is to trust them.", author: "Ernest Hemingway" },
    { quote: "All you have to do is write one true sentence.", author: "Ernest Hemingway" },

    // Writers - Ijeoma Umebinyuo
    { quote: "Start now. Start where you are. Start with fear. Just start.", author: "Ijeoma Umebinyuo" },
    { quote: "You must let the pain visit. You must allow it to teach you.", author: "Ijeoma Umebinyuo" },

    // Writers - Stephen King
    { quote: "Amateurs sit and wait for inspiration. The rest of us just get up and go to work.", author: "Stephen King" },
    { quote: "The scariest moment is always just before you start.", author: "Stephen King" },
    { quote: "Talent is cheaper than table salt. What separates the talented from the successful is hard work.", author: "Stephen King" },
    { quote: "If you want to be a writer, you must do two things: read a lot and write a lot.", author: "Stephen King" },
    { quote: "Get busy living or get busy dying.", author: "Stephen King" },

    // Writers - Others
    { quote: "You can always edit a bad page. You can't edit a blank page.", author: "Jodi Picoult" },
    { quote: "If there's a book you want to read but it hasn't been written yet, write it.", author: "Toni Morrison" },
    { quote: "You don't start out writing good stuff. You start out writing crap.", author: "Octavia E. Butler" },
    { quote: "Write to taste life twice, in the moment and in retrospect.", author: "Anaïs Nin" },
    { quote: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin" },
    { quote: "I can shake off everything as I write; my sorrows disappear.", author: "Anne Frank" },
    { quote: "I write to discover what I know.", author: "Flannery O'Connor" },
    { quote: "The role of a writer is not to say what we can all say, but what we are unable to say.", author: "Anaïs Nin" },
    { quote: "A writer is someone for whom writing is more difficult than it is for other people.", author: "Thomas Mann" },
    { quote: "You must stay drunk on writing so reality cannot destroy you.", author: "Ray Bradbury" },
    { quote: "Words are a form of action, capable of influencing change.", author: "Ingrid Bengis" },
    { quote: "Writing is easy. Just sit down and open a vein.", author: "Red Smith" },

    // Ancient Philosophy
    { quote: "We are what we repeatedly do. Excellence is not an act but a habit.", author: "Aristotle" },
    { quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
    { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { quote: "An unexamined life is not worth living.", author: "Socrates" },
    { quote: "He who conquers himself is the mightiest warrior.", author: "Confucius" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
    { quote: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
    { quote: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
    { quote: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },

    // Modern Leaders & Thinkers
    { quote: "Action expresses priorities.", author: "Mahatma Gandhi" },
    { quote: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
    { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { quote: "Success is not final, failure is not fatal: courage to continue is what counts.", author: "Winston Churchill" },
    { quote: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill" },
    { quote: "You will never reach your destination if you stop to throw stones at every dog that barks.", author: "Winston Churchill" },
    { quote: "If you're going through hell, keep going.", author: "Winston Churchill" },
    { quote: "The price of greatness is responsibility.", author: "Winston Churchill" },
    { quote: "Done is better than perfect.", author: "Sheryl Sandberg" },
    { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { quote: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },

    // Productivity & Business
    { quote: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
    { quote: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
    { quote: "The harder I work, the luckier I get.", author: "Gary Player" },
    { quote: "Small daily improvements are the key to staggering long-term results.", author: "Unknown" },
    { quote: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { quote: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "FDR" },
    { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { quote: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss" },
    { quote: "Discipline equals freedom.", author: "Jocko Willink" },
    { quote: "Expect problems and eat them for breakfast.", author: "Alfred A. Montapert" },
    { quote: "Do the hard jobs first. The easy jobs will take care of themselves.", author: "Dale Carnegie" },
    { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { quote: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
    { quote: "Productivity is never an accident.", author: "Paul J. Meyer" },
    { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { quote: "Be so good they can't ignore you.", author: "Steve Martin" },
    { quote: "Success usually comes to those too busy to be looking for it.", author: "Thoreau" },
    { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { quote: "Great things are done by a series of small things brought together.", author: "Van Gogh" },
    { quote: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
    { quote: "Work hard in silence, let your success be your noise.", author: "Frank Ocean" },
    { quote: "The only person you are destined to become is the person you decide to be.", author: "Emerson" },

    // More Motivational
    { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
    { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { quote: "Quality is not an act, it is a habit.", author: "Aristotle" },
    { quote: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
    { quote: "I hated every minute of training, but I said, don't quit.", author: "Muhammad Ali" },
    { quote: "Champions aren't made in gyms. They're made from something deep inside.", author: "Muhammad Ali" },
    { quote: "If my mind can conceive it, and my heart can believe it, I can achieve it.", author: "Muhammad Ali" },
    { quote: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
    { quote: "I am the greatest. I said that even before I knew I was.", author: "Muhammad Ali" },
    { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { quote: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
    { quote: "It is in your moments of decision that your destiny is shaped.", author: "Tony Robbins" },
    { quote: "The path to success is to take massive, determined action.", author: "Tony Robbins" },
    { quote: "The quality of your life is the quality of your relationships.", author: "Tony Robbins" },
    { quote: "Progress equals happiness.", author: "Tony Robbins" },
    { quote: "Your past does not equal your future.", author: "Tony Robbins" },
    { quote: "Trade your expectations for appreciation.", author: "Tony Robbins" },
    { quote: "The more you praise what you have, the more you have to praise.", author: "Oprah Winfrey" },
    { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
    { quote: "You get in life what you have the courage to ask for.", author: "Oprah Winfrey" },
    { quote: "Think like a queen. A queen is not afraid to fail.", author: "Oprah Winfrey" },
    { quote: "Surround yourself with only people who are going to lift you higher.", author: "Oprah Winfrey" },
    { quote: "Doing the best at this moment puts you in the best place for the next moment.", author: "Oprah Winfrey" },
    { quote: "Create the highest, grandest vision possible for your life.", author: "Oprah Winfrey" },
    { quote: "The more grateful you are, the more beauty you see.", author: "Mary Davis" },
    { quote: "What you seek is seeking you.", author: "Rumi" },
    { quote: "Let yourself be silently drawn by the strange pull of what you really love.", author: "Rumi" },
    { quote: "The wound is the place where the light enters you.", author: "Rumi" },
    { quote: "As you start to walk on the way, the way appears.", author: "Rumi" },
    { quote: "Set your life on fire. Seek those who fan your flames.", author: "Rumi" },
    { quote: "Don't be satisfied with stories. Unfold your own myth.", author: "Rumi" },
    { quote: "Let the beauty of what you love be what you do.", author: "Rumi" },
    { quote: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I change myself.", author: "Rumi" },
    { quote: "Be a lamp, or a lifeboat, or a ladder.", author: "Rumi" },
    { quote: "Raise your words, not your voice. Rain grows flowers, not thunder.", author: "Rumi" },

    // Tech & Entrepreneurship
    { quote: "Move fast and break things.", author: "Mark Zuckerberg" },
    { quote: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
    { quote: "Ideas are easy. Implementation is hard.", author: "Guy Kawasaki" },
    { quote: "If you're not embarrassed by the first version, you've launched too late.", author: "Reid Hoffman" },
    { quote: "The only way to win is to learn faster than anyone else.", author: "Eric Ries" },
    { quote: "There is only one way to avoid criticism: do nothing, say nothing, be nothing.", author: "Aristotle" },
    { quote: "Make every detail perfect and limit the number of details to perfect.", author: "Jack Dorsey" },
    { quote: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
    { quote: "It's fine to celebrate success but it is more important to heed the lessons of failure.", author: "Bill Gates" },
    { quote: "Success is a lousy teacher. It seduces smart people into thinking they can't lose.", author: "Bill Gates" },
    { quote: "Life is not fair; get used to it.", author: "Bill Gates" },
    { quote: "Don't compare yourself to anyone. If you do, you are insulting yourself.", author: "Bill Gates" },
    { quote: "I choose a lazy person to do a hard job. They'll find an easy way to do it.", author: "Bill Gates" },
    { quote: "Patience is a key element of success.", author: "Bill Gates" },
    { quote: "Think different.", author: "Apple" },
    { quote: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
    { quote: "Genius is 1% inspiration and 99% perspiration.", author: "Thomas Edison" },
    { quote: "Many of life's failures are people who did not realize how close they were to success.", author: "Thomas Edison" },
    { quote: "Our greatest weakness lies in giving up. Always try one more time.", author: "Thomas Edison" },
    { quote: "The most certain way to succeed is to try just one more time.", author: "Thomas Edison" },
    { quote: "Imagination is more important than knowledge.", author: "Albert Einstein" },
    { quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { quote: "Try not to become a man of success but rather try to become a man of value.", author: "Albert Einstein" },
    { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { quote: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
    { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { quote: "Once we accept our limits, we go beyond them.", author: "Albert Einstein" },

    // Sports & Athletes
    { quote: "I've failed over and over again. That is why I succeed.", author: "Michael Jordan" },
    { quote: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
    { quote: "Obstacles don't have to stop you.", author: "Michael Jordan" },
    { quote: "I can accept failure, everyone fails. I can't accept not trying.", author: "Michael Jordan" },
    { quote: "My attitude is that if you push me, I will push back.", author: "Michael Jordan" },
    { quote: "I play to win, whether in practice or a real game.", author: "Michael Jordan" },
    { quote: "The only way to prove you are a good sport is to lose.", author: "Ernie Banks" },
    { quote: "It's not whether you get knocked down; it's whether you get up.", author: "Vince Lombardi" },
    { quote: "Winners never quit and quitters never win.", author: "Vince Lombardi" },
    { quote: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
    { quote: "It's not the will to win that matters—everyone has that. It's the will to prepare to win.", author: "Bear Bryant" },
    { quote: "You were born to win, but to be a winner, you must plan, prepare, and expect to win.", author: "Zig Ziglar" },
    { quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
    { quote: "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
    { quote: "Be water, my friend.", author: "Bruce Lee" },
    { quote: "Absorb what is useful, reject what is useless, add what is essentially your own.", author: "Bruce Lee" },
    { quote: "To hell with circumstances; I create opportunities.", author: "Bruce Lee" },
    { quote: "Adapt what is useful, reject what is useless.", author: "Bruce Lee" },
    { quote: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Bruce Lee" },

    // Short & Punchy (with meaning)
    { quote: "Trust the process.", author: "Unknown" },
    { quote: "Prove them wrong.", author: "Unknown" },
]

// Get a random quote
export function getRandomQuote(): { quote: string; author: string } {
    const index = Math.floor(Math.random() * bossQuotes.length)
    return bossQuotes[index]
}

// Format quote with attribution
export function formatQuoteWithAuthor(quoteObj: { quote: string; author: string }): string {
    return `"${quoteObj.quote}" — ${quoteObj.author}`
}
